### ISSUE TITLE
Add typing to the `app.config`

### ISSUE THREAD

**Issue by Atinux** [nuxt-themes/starter#6]
Example: https://github.com/nuxt-modules/icon/blob/main/src/module.ts#L5-L13

In which file would you recommend to add the types @pi0?

**Comment by pi0** [comment]
The main module seems good  👍🏼

**Comment by Atinux** [comment]
You mean in https://github.com/nuxt-themes/starter/blob/main/theme/app.config.ts ?

**Comment by pi0** [comment]
Moved to discussion https://github.com/nuxt/framework/issues/7373
